version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=${DJANGO_SECRET_KEY}
    volumes:
      - ./backend:/app
      - db_data:/app/db.sqlite3
    networks:
      - movai_network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000/api
    networks:
      - movai_network

volumes:
  db_data:

networks:
  movai_network:
    driver: bridge