# Generated by Django 6.0.5 on 2026-05-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaClima',
            fields=[
                ('id_alerta_clima', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Alerta Clima')),
                ('nivel_precipitacion', models.FloatField(help_text='Intensidad de lluvia en milímetros por hora', verbose_name='Nivel de Precipitación (mm/h)')),
                ('estado_clima', models.CharField(choices=[('tormenta', 'Tormenta'), ('lluvia_fuerte', 'Lluvia Fuerte'), ('lluvia_moderada', 'Lluvia Moderada'), ('lluvia_ligera', 'Lluvia Ligera'), ('niebla', 'Niebla'), ('normal', 'Normal')], max_length=50, verbose_name='Estado del Clima')),
                ('coordenadas_afectadas', models.JSONField(blank=True, help_text='FeatureCollection GeoJSON con las áreas o puntos afectados', null=True, verbose_name='Coordenadas Afectadas (GeoJSON)')),
                ('fuente_api', models.CharField(default='openweathermap', max_length=50, verbose_name='API de Origen')),
                ('activa', models.BooleanField(default=True, help_text='Si la alerta sigue vigente o ya expiró', verbose_name='Alerta Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Momento en que la alerta pierde vigencia', null=True, verbose_name='Expira')),
            ],
            options={
                'verbose_name': 'Alerta Climática',
                'verbose_name_plural': 'Alertas Climáticas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Navegacion',
            fields=[
                ('id_navegacion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Navegación')),
                ('id_cliente', models.IntegerField(blank=True, help_text='ID del usuario si está autenticado (null = anónimo)', null=True, verbose_name='ID Cliente')),
                ('origen', models.JSONField(verbose_name='Origen {lat, lng}')),
                ('destino', models.JSONField(verbose_name='Destino {lat, lng}')),
                ('ruta_segura_coordenadas', models.JSONField(help_text='FeatureCollection GeoJSON con la polyline de la ruta recomendada', verbose_name='Ruta Segura (GeoJSON)')),
                ('restricciones_evitadas', models.CharField(blank=True, help_text='Lista separada por comas de las vías/zonas peligrosas evitadas', max_length=500, null=True, verbose_name='Restricciones Evitadas')),
                ('tiempo_estimado', models.IntegerField(blank=True, null=True, verbose_name='Tiempo Estimado (segundos)')),
                ('distancia', models.FloatField(blank=True, null=True, verbose_name='Distancia (km)')),
                ('modo_lluvias', models.BooleanField(default=True, verbose_name='Modo Temporada de Lluvias Activo')),
                ('riesgo_promedio', models.FloatField(blank=True, null=True, verbose_name='Riesgo Promedio (0.0 - 1.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Navegación',
                'verbose_name_plural': 'Navegaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaAccidente',
            fields=[
                ('id_estadistica', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Estadística')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('nivel_precipitacion', models.FloatField(help_text='Precipitación acumulada del día', verbose_name='Precipitación (mm)')),
                ('num_accidentes', models.IntegerField(default=0, verbose_name='Número de Accidentes')),
                ('zonas_afectadas', models.JSONField(blank=True, help_text='Puntos de accidentes ocurridos en esa fecha', null=True, verbose_name='Zonas Afectadas (GeoJSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Estadística de Accidente',
                'verbose_name_plural': 'Estadísticas de Accidentes',
                'ordering': ['-fecha'],
                'unique_together': {('fecha',)},
            },
        ),
        migrations.CreateModel(
            name='ZonaRiesgo',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Zona')),
                ('tipo', models.CharField(choices=[('inundacion', 'Riesgo de Inundación'), ('sensor_nivel', 'Sensor de Nivel (Arroyo)'), ('accidentalidad', 'Punto de Accidentalidad')], max_length=30, verbose_name='Tipo de Riesgo')),
                ('geometria', models.JSONField(help_text='Geometría en GeoJSON: Point, Polygon o MultiPolygon en WGS84', verbose_name='Geometría (GeoJSON)')),
                ('nivel_riesgo', models.IntegerField(default=1, help_text='1 = riesgo bajo, 5 = riesgo crítico', verbose_name='Nivel de Riesgo (1-5)')),
                ('fuente', models.CharField(default='alcaldia_medellin', max_length=50, verbose_name='Fuente del Dato')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('subcuenca', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subcuenca')),
                ('comuna', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comuna')),
                ('barrio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Barrio')),
                ('gravedad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gravedad')),
                ('fecha_evento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Evento')),
                ('metadata_original', models.JSONField(blank=True, help_text='Propiedades completas del feature original en el GeoJSON', null=True, verbose_name='Metadatos Originales')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Zona de Riesgo',
                'verbose_name_plural': 'Zonas de Riesgo',
                'indexes': [models.Index(fields=['tipo'], name='MovAI_zonar_tipo_496a63_idx'), models.Index(fields=['nivel_riesgo'], name='MovAI_zonar_nivel_r_caeb6e_idx')],
            },
        ),
    ]
