# Generated by Django 6.0.5 on 2026-05-28 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_mapa_lat', models.FloatField(default=6.2476)),
                ('centro_mapa_lng', models.FloatField(default=-75.5658)),
                ('zoom_default', models.IntegerField(default=13)),
                ('intervalo_refresco', models.IntegerField(default=300, help_text='Intervalo en segundos (5 min)')),
                ('eventos_limite', models.IntegerField(default=20, help_text='Máx eventos recientes en la respuesta')),
                ('segmentos_monitoreados', models.IntegerField(default=12, help_text='Top N segmentos más importantes a monitorear')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Dashboard',
            },
        ),
        migrations.CreateModel(
            name='InfraestructuraFija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('CAMARA_ARS', 'Cámara ARS'), ('CAMARA_FDT', 'Cámara Fotodetección'), ('SEMAFORO', 'Cruce Semafórico'), ('PMV', 'Panel de Mensajería Variable'), ('SEDE', 'Sede Movilidad'), ('RADAR', 'Radar Estático')], max_length=20)),
                ('ubicacion', models.JSONField(help_text='Coordenadas del punto [lng, lat] o GeoJSON Point')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RutaSugerida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadas_trayecto', models.TextField(help_text='GeoJSON LineString de la ruta alterna')),
                ('tiempo_estimado_original', models.IntegerField(help_text='Tiempo original estimado en segundos')),
                ('tiempo_estimado_alterno', models.IntegerField(help_text='Tiempo alternativo estimado en segundos')),
                ('ahorro_porcentaje', models.FloatField(help_text='Porcentaje de ahorro calculado')),
                ('ahorro_segundos', models.IntegerField(help_text='Ahorro absoluto en segundos')),
                ('cumple_regla', models.BooleanField(default=False, help_text='True si ahorro >= 15% o >= 300s')),
                ('distancia_km', models.FloatField()),
                ('origen_coords', models.CharField(help_text='lat,lng', max_length=100)),
                ('destino_coords', models.CharField(help_text='lat,lng', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fue_aceptada', models.BooleanField(default=False)),
                ('aceptada_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ruta Sugerida',
                'verbose_name_plural': 'Rutas Sugeridas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RegistroKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALERTA_ENVIADA', 'Alerta de congestión enviada'), ('RUTA_SUGERIDA', 'Ruta alterna sugerida'), ('RUTA_ACEPTADA', 'Ruta alterna aceptada por el usuario'), ('TIEMPO_RESPUESTA_MS', 'Tiempo de respuesta del sistema (ms)'), ('ERROR_API', 'Error en API externa (TomTom/HERE)'), ('CICLO_COMPLETADO', 'Ciclo de actualización completado')], db_index=True, max_length=30)),
                ('valor', models.FloatField(help_text='Valor del KPI (conteo, ms, etc.)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales (segmento_id, api, error_msg, etc.)')),
            ],
            options={
                'verbose_name': 'Registro KPI',
                'verbose_name_plural': 'Registros KPI',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tipo', 'timestamp'], name='MovAI_regis_tipo_5d6f15_idx')],
            },
        ),
        migrations.CreateModel(
            name='SegmentoVial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField(blank=True, help_text='OBJECTID del GeoJSON de la Alcaldía', null=True, unique=True)),
                ('nombre', models.CharField(blank=True, default='', help_text='Nombre compuesto tipo_via + numero_via + apendice, ej. CL 104B', max_length=255)),
                ('label', models.CharField(blank=True, default='', help_text='Label corto del GeoJSON, ej. CL 104B', max_length=255)),
                ('nombre_comun', models.CharField(blank=True, default='', help_text='Nombre común o sector, ej. BOMBONA', max_length=255)),
                ('via_principal', models.CharField(blank=True, default='', max_length=100)),
                ('via_generadora', models.CharField(blank=True, default='', max_length=100)),
                ('tipo_via', models.CharField(blank=True, default='', help_text='CL = Calle, CR = Carrera, AV = Avenida, DG = Diagonal, etc.', max_length=10)),
                ('sentido', models.CharField(blank=True, default='', max_length=50)),
                ('velocidad_maxima', models.IntegerField(default=50, help_text='km/h')),
                ('jerarquia_via', models.IntegerField(blank=True, help_text='Jerarquía: menor número = vía más importante (arteria)', null=True)),
                ('comuna', models.CharField(blank=True, default='', max_length=10)),
                ('municipio', models.CharField(blank=True, default='MEDELLIN', max_length=100)),
                ('longitud_m', models.FloatField(blank=True, help_text='Longitud del segmento en metros', null=True)),
                ('geometria', models.JSONField(help_text='GeoJSON LineString original (proyectado EPSG:9377)')),
                ('geometria_wgs84', models.JSONField(blank=True, help_text='GeoJSON LineString transformado a WGS84 (lat/lng)', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si está activo para monitoreo de tráfico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Segmento Vial',
                'verbose_name_plural': 'Segmentos Viales',
                'indexes': [models.Index(fields=['jerarquia_via'], name='MovAI_segme_jerarqu_8544f9_idx'), models.Index(fields=['activo'], name='MovAI_segme_activo_689523_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlujoVehicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen', models.IntegerField(default=0, help_text='Vehículos por hora (si la fuente lo provee)')),
                ('velocidad_promedio', models.FloatField(help_text='Velocidad actual en km/h')),
                ('velocidad_libre', models.FloatField(blank=True, help_text='Velocidad sin congestión (free flow) en km/h', null=True)),
                ('nivel_congestion', models.CharField(choices=[('BAJO', 'Bajo'), ('MODERADO', 'Moderado'), ('ALTO', 'Alto'), ('SEVERO', 'Severo')], default='BAJO', max_length=10)),
                ('congestionado', models.BooleanField(default=False)),
                ('fuente', models.CharField(default='tomtom', help_text='Fuente del dato: tomtom, here, mapa_colaborativo', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flujos', to='MovAI.segmentovial')),
            ],
            options={
                'verbose_name': 'Flujo Vehicular',
                'verbose_name_plural': 'Flujos Vehiculares',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['segmento', '-timestamp'], name='MovAI_flujo_segment_22a2a3_idx'), models.Index(fields=['congestionado'], name='MovAI_flujo_congest_9d0061_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventoCongestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('BAJO', 'Bajo'), ('MODERADO', 'Moderado'), ('ALTO', 'Alto'), ('SEVERO', 'Severo')], max_length=10)),
                ('velocidad_promedio', models.FloatField()),
                ('velocidad_libre', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='MovAI.segmentovial')),
            ],
            options={
                'verbose_name': 'Evento de Congestión',
                'verbose_name_plural': 'Eventos de Congestión',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['activo', '-timestamp'], name='MovAI_event_activo_38a74d_idx'), models.Index(fields=['segmento', 'activo'], name='MovAI_event_segment_6df609_idx')],
            },
        ),
    ]
