# Generated by Django 4.2.7 on 2026-05-28 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfraestructuraFija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('CAMARA_ARS', 'Cámara ARS'), ('CAMARA_FDT', 'Cámara Fotodetección'), ('SEMAFORO', 'Cruce Semafórico'), ('PMV', 'Panel de Mensajería Variable'), ('SEDE', 'Sede Movilidad'), ('RADAR', 'Radar Estático')], max_length=20)),
                ('ubicacion', models.JSONField(help_text='Coordenadas del punto [lng, lat] o GeoJSON Point')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentoVial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('sentido', models.CharField(max_length=50)),
                ('velocidad_maxima', models.IntegerField(default=50)),
                ('geometria', models.JSONField(help_text='GeoJSON LineString de la vía')),
            ],
        ),
        migrations.CreateModel(
            name='ZonaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('PICO_Y_PLACA', 'Zona Pico y Placa'), ('VIA_EXENTA', 'Vía Exenta')], max_length=20)),
                ('geometria', models.JSONField(help_text='GeoJSON Polygon de la zona')),
            ],
        ),
        migrations.CreateModel(
            name='FlujoVehicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen', models.IntegerField(help_text='Vehículos por hora')),
                ('velocidad_promedio', models.FloatField(help_text='Velocidad en km/h')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('congestionado', models.BooleanField(default=False)),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flujos', to='MovAI.segmentovial')),
            ],
        ),
    ]
