# Generated by Django 6.0.5 on 2026-05-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovAI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navegacion',
            name='id_cliente',
            field=models.CharField(blank=True, help_text='UUID del cliente generado en frontend y guardado en localStorage', max_length=100, null=True, verbose_name='ID Cliente'),
        ),
    ]
